### PR TITLE
Add Water Gardens map icon from BG1NPCSoA.

### PR DESCRIPTION
**Pull request by GraionDilach**
image

### CODE REVIEW

**Comment by Roberciiik** [comment]
Could you please check how it looks like with FfT modification? Government dist. might intersect with Water Gardens.

**Comment by GraionDilach** [comment]
Will test with https://github.com/InfinityMods/FishingForTrouble/pull/7 at home.

I'm not sure what to do against a potential overlap though since the default icons are cropped out from the worldmap itself and this one  is supposed to redefine the body of water under it.

**Comment by Roberciiik** [comment]
I hope there is no overlap. In case it is - we could move Gov. Dist. a bit...

**Comment by GraionDilach** [comment]
On the other hand, because I don't intend to introduce location overrides/duplicates for that mod in this one, that's a problem for  https://github.com/SpellholdStudios/BG1_NPCs_for_SoA_-_ToB/pull/3 and shouldn't be a blocker for this PR.

**Comment by weigo87** [comment]
Another solution would be to make the icons a bit smaller. Then we should have space for FFT and for Water Gardens.

**Comment by weigo87** [comment]
2023-02-08 19_04_56-Near Infinity - Baldur's Gate - Enhanced Edition Trilogy
This is how it looks with both mods. Move the FFT a bit north and maybe make the Water Gardens a bit smaller.

**Comment by GraionDilach** [comment]
Sizes seem fine in EET and I believe the two mods use the same scale for Athkatla. I'm not convinced that this mod's icon is oversized.

image

I'll shift the icon a bit to bottom left for this worldmap.

**Comment by weigo87** [comment]
That Looks Great 😁👍

**Comment by GraionDilach** [comment]
TBH, reviewing this again, I don't oppose a potential future smaller worldmap icon (it has a fountain statue at the center of the map which would look more befitting and this current one seems more appropriate for a lake in the plains) but this is the icon the mod ships with currently.

**Comment by GraionDilach** [comment]
Updated https://github.com/SpellholdStudios/BG1_NPCs_for_SoA_-_ToB/pull/3 with the new map coords. Requesting merge on this one.

**Comment by Roberciiik** [comment]
Could you please post final result along with fft? Also, THERE IS kind of a pond on the original Athkatla map already, so I thought that Water Gardens would match the same position with the pond. From the last picture, we can see two ponds together. It would be nice to move Gov. Dist. a bit higher to make some space for Water Gardens.

**Comment by GraionDilach** [comment]
I didn't touched Gov. Dist West here because @TotoR115's PR is still in the pipeline. I also thought Water Gardens would override the pond, but that's not the case (and I wouldn't move the OG areas because their icons are map cutouts).

I'll try to attempt creating that fountain icon, because that would ensure all these issues would be resolved. I mean, the actual area looks like this:

ARBGX2

I don't know how the area-icon association came up either.

**Comment by GraionDilach** [comment]
OKay, the association makes sense, but it's loose. The walkway at the bottom right edge leads to the pond of the icon, but this is the area where the worldmap leads to.

**Comment by Roberciiik** [comment]
> I didn't touched Gov. Dist West here because @TotoR115's PR is still in the pipeline.

Sure. Maybe we & @TotoR115 could agree to update also FfT PR to move Gov. Dist. a bit and then, you could update [fft_comapt](https://github.com/SpellholdStudios/BP-BGT-Worldmap/blob/master/bp-bgt-worldmap/compat/fft/areas.tbl) and [fft_areas](https://github.com/SpellholdStudios/BP-BGT-Worldmap/blob/master/bp-bgt-worldmap/original/tbl/updates/fft_areas.tbl) files accordingly the same way. Then both icons would work.

**Comment by TotoR115** [comment]
Sure, I will tests this when I can. 
Could someone tell me the exact position of the water garden with worldmap ? Has it been modified ?

**Comment by GraionDilach** [comment]
It's 1140 2875 in it's latest release from this week (the one where it uses the Oasis icon) and tweaked to 1130 2900 in https://github.com/SpellholdStudios/BG1_NPCs_for_SoA_-_ToB/pull/3. I don't intend to modify it in this mod.

**Comment by weigo87** [comment]
Is it possible that NearInfinity or Dltcp made a mistake when packing the pvrz files or is the problem with the map icon in bam v2 format on my computer?

**Comment by GraionDilach** [comment]
It works for me, I'm not sure how to proceed.

image

I did packed it with NearInfinity, but I don't know what could the issue be.

**Comment by TotoR115** [comment]
Position of the map icon was too low with bp-worlmap in comparison with regular BG2 map. The icon has been move up to y = 2810. PR has been updated: https://github.com/InfinityMods/FishingForTrouble/pull/7/commits/23b517934a5b3c2275d785399069668d24cbc650

@GraionDilach, y = 2900 seem too low with worlmap y = 2875 looks better for me...

**Comment by weigo87** [comment]
> It works for me, I'm not sure how to proceed.

Probably an error of my NearInfinity. It showed me the icons with wrong graphics. But now it seems with me also again correctly :) I'll finish the PR.

**Comment by Roberciiik** [comment]
@GraionDilach Could you post the final result? With updated FfT.

**Comment by GraionDilach** [comment]
image

**Comment by Roberciiik** [comment]
@TotoR115 Do we need to update FfT coords for Govt. West in the BP-BGT-Worldmap?

**Comment by GraionDilach** [comment]
@Roberciiik Yes, https://github.com/SpellholdStudios/BP-BGT-Worldmap/blob/master/bp-bgt-worldmap/original/tbl/updates/fft_areas.tbl#L6 voids https://github.com/InfinityMods/FishingForTrouble/commit/23b517934a5b3c2275d785399069668d24cbc650. I had to manually override this later to provide accurate proposal.

**Comment by Roberciiik** [comment]
Great! I will file a PR soon. Thank you for all the work here!

**Pull request merged**
