### PR TITLE
Fix map image and SoD locations to better fit SoD original map.

### PR DESCRIPTION
**Pull request by abalabokhin**
Map image and SoD location positions were changed to better fit SoD original map and storyline (e.g bridges on the rivers, Dead Man's Pass in the mountains, etc), thanks to p_zombie from https://arcanecoast.ru/.
Currently BP-BGT-Worldmap map with SoD locations looks like:
Old
SoD original map is:
Orig
The map after proposed changes looks like:
New

### CODE REVIEW

**Comment by Roberciiik** [comment]
Please verify with other mods that add locations in the similar place if they are not overlapping (at least Shadows over Soubar, NTotSC, DSotSC comes to my mind). It might need some adjustment.

**Comment by abalabokhin** [comment]
> Please verify with other mods that add locations in the similar place if they are not overlapping (at least Shadows over Soubar, NTotSC, DSotSC comes to my mind). It might need some adjustment.
Yes, it was tested and all the locations re-positioned, considering other modes (definitely the ones you mentioned), see the map with other modes installed (sorry, it is in Russian, but the icons are there).

**Comment by Roberciiik** [comment]
Great, thanks!

**Comment by weigo87** [comment]
It would be nice if we could change the maps worldmap_small.mos and worlmap_larg.mos in the other languages as well.

**Comment by abalabokhin** [comment]
We have Russian and French versions. Do you want to keep updated maps for different languages in this repository or in dedicated ones like before (eg https://github.com/SpellholdStudios/BP-BGT-Worldmap_Russian_addon/)?

**Comment by weigo87** [comment]
It would be great if you could create the other languages as well and publish them in the appropriate (eg https://github.com/SpellholdStudios/BP-BGT-Worldmap_Russian_addon/) repositories. I have here a link to the original files of the world map (https://github.com/weigo87/BP-BGT-Worldmap-Source-Files) Thanks in advance for your commitment.

**Comment by abalabokhin** [comment]
I ask p_zombie from arcanecoast.ru to redo the maps (he actually was doing all the work before), and he found out that Winding Water should start at March of Chelimber, not intersect with River Chionthar. (https://forgottenrealms.fandom.com/wiki/Marsh_of_Chelimber) So, we want to redo the image map one more time (no location reposition are involved, cause it is only about the beginning of the river, not the end of it (that is used in SoD)). Can you verify that you will accept these changes, so we don't do it for nothing, please?

It is how it looks in the game:

And here is the xcf file for the changed map:
https://www.mediafire.com/view/70ou6sf0mnqsg40/BP-BGT_Worldmap_v11.xcf/file

**Comment by weigo87** [comment]
The map looks great. Unfortunately, the Russian and French translation is not part of the gimp file. Which of the language versions are ready? I could finish the others this weekend. And thanks again for the creative work on the world map.

**Comment by abalabokhin** [comment]
He prepared Russian and French maps (by working with images, since there are no these languages in xcf file), see pull requests: https://github.com/SpellholdStudios/BP-BGT-Worldmap_French_addon/pull/2, https://github.com/SpellholdStudios/BP-BGT-Worldmap_Russian_addon/pull/2. However, he is not very familiar with gimp and it would be nice if you can prepare other maps from the xcf file.

Thank you!

**Comment by weigo87** [comment]
No problem. I will finish the other languages this weekend and upload it to the github. :)
So we have a wonderful v11 pack.

**Comment by weigo87** [comment]
All maps are uploaded. English, German, Italian, Polish and Spanish.
In which format do you have the French and Russian translations?
I have reworked the Gimp file the last few days and have designed many subgroups for the layer, so that you can change the language and size with only 3 mouse clicks and do not have to click as before every single layer (hundreds of layers).
It would be great to have everything together or at least have the image files with on this github https://github.com/weigo87/BP-BGT-Worldmap-Source-Files

**Comment by abalabokhin** [comment]
Russian and French map were editing directly as png files. You can get them from here https://www.mediafire.com/file/mrl4cby5nm9nj2o/BP-BGT-Worldmap-update-FR-RU-V11.ZIP/file.
Unfortunately, he is not ready to add new layers for these languages to xcf file now - it is too much work now, maybe later (we even don't have the proper font). Thus, I think the best thing to do now is to add these png files to the repo with sources.

Can you also consider adding all the maps for all the languages into main mod repo, please? I think the main reason why there are many repositories was to save space and traffic. I don't think it is relevant any more. It is not very convenient to work with two repos (two zip files) if you want to install the mod for any other language but English.

**Comment by Roberciiik** [comment]
> Can you also consider adding all the maps for all the languages into main mod repo, please?

@weigo87 I like this idea too. We could release v11 of addons and in the meantime new version of Worldmap with addons implemented inside one mod.

**Comment by weigo87** [comment]
I raised the issue with jastey as a modarator, as I would like it too, but would like to get her opinion.
The transcription into the Cyrillic alphabet makes it more difficult for the world map, since every name is written in Cyrillic. French would be much easier. Maybe I will find time for it during my next vacation.
Therefore I will first upload the two png files into the source repository, so that we have everything nicely together.

**Pull request merged**
