### PR TITLE
Fix Dragonspear UI thanks to p_zombie from arcanecoast.ru

### PR DESCRIPTION
**Pull request by abalabokhin**
It was fixed, so it better works with different resolutions and no has drag problems.

### CODE REVIEW

**Comment by weigo87** [comment]
Is the area button necessary?

**Comment by abalabokhin** [comment]
Do you think it is better to remove it?

**Comment by weigo87** [comment]
It looks prettier without. How urgent is it for the Android user?

**Comment by abalabokhin** [comment]
I would assume that without this button, android users cannot close the map, since they cannot press ESC button, but I cannot test it now. Generally, I believe there should be the way to close the map without using keyboard (using UI elements along). This button can be made smaller/combined with other UI elements, though.

However, this changes are only for dragonspear UI, and if you think, that this button should be removed, I can do it. It is up to you.

**Comment by weigo87** [comment]
Everything OK. If the need because of the Android version because of the missing ESC button, then let's do it with the button. I will publish it like that, should I think of anything prettier, like you also mentioned, then I will change the design again. Thanks again for your help. :)

**Pull request merged**
