### PR TITLE
Update Russian moz file to have a dedicated Neverwinter window and add icons for Neverwinter districts

### PR DESCRIPTION
**Pull request by abalabokhin**
I am extracting a mod (https://github.com/abalabokhin/NWNForBG) from an assembly made by AGKanevchev that repeats NWN plot. For that I need to add a dedicated window for Neverwinter and some icons for its districts. In this pull request, the map (only Russian version for now) was changed by p_zombie and 5 new icons were added for Neverwinter districts. The map should look like this: https://www.mediafire.com/view/3kgodiy1mv3jots/04-worldmap_large-nw7.png/file#. 

The Waterdeep window was moved down a little and zoomed out. As far as I know no mods uses the Waterdeep window, so this should not be the issue. If the map change is acceptable, p_zombie agreed to change the map in BP-BGT-Woaldmap-Source-Files.

### CODE REVIEW

**Comment by Roberciiik** [comment]
Thanks! I will test it soon. The one issue here - I think Roxanne's Sandrah Saga uses Waterdeep city map, so moving it will introduce some incompatibility. Is there any chance to fit Neverwinter without moving the Waterdeep?

**Comment by abalabokhin** [comment]
Sandrah saga doesn't use the Waterdeep window, here is her answer about it

> Just some additional remarks with respect to the pictures.
> - Sandrah mod does not use the Waterdeep insert map but just one single icon on the mainland (once you go into town, you move to other areas via street end transitions, not by worldmap).
> - No mod ever used Luskan or the inserts for that town.
> - The only inserts ever used by mods were Hlondeth (by a CtB module) and island Lendore (By Bone Hill mod).
> An option might be to remove the Luskan and Waterdeep inserts to have room for Neverwinter. 

from here:  https://arcanecoast.ru/forum/viewtopic.php?p=2200922#p2200922. However, NWNForBG needs Luskan, so we don't remove its window, as she suggested.

Thus, it should be safe to move the Waterdeep window a little. p_zombie tried adding a Nevewrinter window without moving the Waterdeep one, but it looks ugly (IMHO):
https://www.mediafire.com/view/od0es5sl8eh06xy/%25D0%2591%25D0%25B5%25D0%25B7_%25D0%25B8%25D0%25BC%25D0%25B5%25D0%25BD%25D0%25B8-4.jpg/file#

We will do, as you say, but, please, consider the version from the pull request, first.

**Comment by Roberciiik** [comment]
Could you post English map screenshot as well?

**Comment by abalabokhin** [comment]
Sure: https://www.mediafire.com/view/xvflrlmuoy0bi9w/worldmap_large.png/file
If you need the whole png file, you can take it from here: https://www.mediafire.com/file/h28irx9sfnr2jid/worldmap_large.zip/file

PS p_zombie is still working on the map, it is not the final version.

**Comment by abalabokhin** [comment]
Actually, p_zombie finished redoing maps, this is the screenshot: https://www.mediafire.com/view/wv9pllolfqt20w6/en1.jpg/file#
He added Beorunna's Well and moved The Craigs a little. He also said, that he prepared bp-bgt-worldmap-source, added Beorunna's Well and Port Llast layers (no translation for all the languages though). Once the map change is confirmed, I can send a pull request into bp-bgt-worldmap-source repo.

**Comment by abalabokhin** [comment]
I also updated pull request to add changed English map if you want to look at it in the game.

**Comment by Roberciiik** [comment]
Hi @abalabokhin 
I've installed English version of NWN-for-BG and BP-BGT-Worldmap, and moz file of Worldmap looks fine. One issue here is to remove the label "Port Llast" from the area icons because it is already on the moz label.

Additional question is: are you guys able to prepare a moz file for the rest of languages if the translation of "Beorunna's Well" and "Port Llast" were provided for you?

**Comment by abalabokhin** [comment]
Yes, p_zombie is ready to generate other moz files for other languages from the sources if the translation is provided. Updating Russian and French maps will take some time, cause they are not in sources, though.

**Comment by Roberciiik** [comment]
I opened the discussion on G3 to collect the proper translations from the community: https://www.gibberlings3.net/forums/topic/37058-translation-needed-translation-for-neverwinter-night-locations/.

**Comment by Roberciiik** [comment]
@abalabokhin Do you have original BAM/PNG files of new icons? I will need the source files to recreate the icon file for oBG2 in a near future.

**Comment by abalabokhin** [comment]
I updated the pull request with the maps for all the languages kindly prepared by p_zombie. He also provided changed xcf file, that he used to generate the maps (for all the languages but Russian and French): https://www.mediafire.com/file/frumba38z90jpuf/BP-BGT_Worldmap_v11_1-src-009e-nwn.zip/file. I believe this repo (https://github.com/weigo87/BP-BGT-Worldmap-Source-Files) should be updated with this file.

The icons that are included in #46 and in this pull request are the only ones I have. I asked the original NWN assembly author (AGKanevchev) if he has something better, but very likely he doesn't have anything else. I will let you know once I have an update from him.

**Comment by Roberciiik** [comment]
Great! I will check Worldmap for all languages. And also file a PR for xcf file in the source repo. 

Let's keep this PR opened until you get the response. Then we will see if we need to update the icon file.

Thank you all for this work!

**Comment by abalabokhin** [comment]
He actually does have the original files (bmp), you can take them from here: https://www.mediafire.com/file/00m44993znq7vgz/nwn_icons.zip/file
I hope it is what you need, cause we don't have anything else.

**Comment by Roberciiik** [comment]
Hello @abalabokhin. Do you (or p_zombie) have original MOS file of updated Russian and French worldmap_large files? We want to switch to lossless compression format MBC here #52, but we need to generate the worldmap with Neverwinter from original files. Included MOZ are JPG compression, so it looses some details.

**Pull request merged**
