### PR TITLE
Add zh_CN translations

### PR DESCRIPTION
**Pull request by MephistoSatanDevil**

### CODE REVIEW

**Review by Roberciiik — CHANGES_REQUESTED** [review]

**Comment by Roberciiik** [comment]
Hello @MephistoSatanDevil. First of all, thank you for creating this pull request. We are happy for community contributions. As I pointed in the review, there is an issue with improper UTF-8 format. Will you update your changes according to this?

**Comment by Roberciiik** [comment]
Please verify if #57 is working properly.

**Comment by Roberciiik** [comment]
Closing as those translations was merged in #57

**Comment by MephistoSatanDevil** [comment]
> Closing as those translations was merged in #57

Sorry for reply later.
BG2EE require UTF-8 codepage and classic BG2 require gb2312, but I have no idea how to slove the problem.

**Comment by Roberciiik** [comment]
Hello,
Most modifications keep translation in native page code and do convertion to UTF-8 on the fly during mod installation. In BP-BGT-Worldmap it is the same - .tra files have to be in GB2312/CP936.

I did the convertion to native before publishing a new version. Could you check if the translations are fine on BG2EE?

**Comment by MephistoSatanDevil** [comment]
> Hello, Most modifications keep translation in native page code and do convertion to UTF-8 on the fly during mod installation. In BP-BGT-Worldmap it is the same - .tra files have to be in GB2312/CP936.
> 
> I did the convertion to native before publishing a new version. Could you check if the translations are fine on BG2EE?

It is fine on BG2EE.
But during the installation of BG2 Classic, all Chinese characters are displayed as garbled. And during BG2EE installation, the first two lines of Chinese characters are displayed as gibberish (The red box in the attached picture shows the location of the garbled code).
bc

**Comment by Roberciiik** [comment]
Hello,

Thank you for the feedback!

> And during BG2EE installation, the first two lines of Chinese characters are displayed as gibberish (The red box in the attached picture shows the location of the garbled code).

I will double-check that, but probably Windows Terminal Console is not supporting Chinese characters. In this case, there is a suggestion to use English component names for the setup installation process (example is Russian setup files, where there are three versions of page code for Windows Console). 

> But during the installation of BG2 Classic, all Chinese characters are displayed as garbled. 

That's a shame. :/ Are you able to convert this incorrect code page that I used to the one supported by your game?

**Comment by MephistoSatanDevil** [comment]
> Hello,
> 
> Thank you for the feedback!
> 
> > And during BG2EE installation, the first two lines of Chinese characters are displayed as gibberish (The red box in the attached picture shows the location of the garbled code).
> 
> I will double-check that, but probably Windows Terminal Console is not supporting Chinese characters. In this case, there is a suggestion to use English component names for the setup installation process (example is Russian setup files, where there are three versions of page code for Windows Console).
> 
> > But during the installation of BG2 Classic, all Chinese characters are displayed as garbled.
> 
> That's a shame. :/ Are you able to convert this incorrect code page that I used to the one supported by your game?

Hi,
After some chinese modder discussion, we think this is fine for now. No matter which code page is used there is no perfect solution to this problem. So just keep it as it is, until we find the perfect solution.
If we find any other issues, I'll submit a fix.
😀

**Comment by Roberciiik** [comment]
Great! If you find a proper code page or better translation in the other way, let us know so we will update the modification. Thanks for the support.

**Comment by ALIENQuake** [comment]
@MephistoSatanDevil Hi, you can use PI to install this mod, it should display component names correctly.

**Pull request closed without merging**
