### PR TITLE
Corrected three Chinese translations of place names:

### PR DESCRIPTION
**Pull request by MephistoSatanDevil**
Trademeet (this translation error has existed for twenty years), Saradush, Luskan

### CODE REVIEW

**Comment by Roberciiik** [comment]
Could you please also update the Worldmap Source XCF files to fix translation issues in the source as well.

**Comment by MephistoSatanDevil** [comment]
> n issues in the source as well.

Done.

**Comment by Roberciiik** [comment]
@MephistoSatanDevil 
Could you please check if all command-line prompts are correctly translated to Chinese? When I tested your change, it seems that after HANDLE_CHARSET reload, Chinese prompts changed back to English. If this is the case, could you please verify it and fix eventually?

**Comment by MephistoSatanDevil** [comment]
> @MephistoSatanDevil Could you please check if all command-line prompts are correctly translated to Chinese? When I tested your change, it seems that after HANDLE_CHARSET reload, Chinese prompts changed back to English. If this is the case, could you please verify it and fix eventually?

When I install on EET, only the option "Worldmap for Baldur's Gate - including colored Baldur's Gate map icons (@1000)" is correctly checked in Chinese, while the options "Which travel times do you want? (@2000)", "Which size of the worldmap do you want? (@3000)", "Worldmap for Throne of Bhaal (@4000)", and "Convert old Savegames (No 'New Game' needed) (@5000)" are all not displayed.

The option "Larger worldmap screen window for the worldmap menu.ui" and its sub-options "BG2 style" and "Dragonspear style" are all originally in the tp2 file, and cannot be translated.

Is this correct?

**Comment by Roberciiik** [comment]
I think it is NOT correct. I think that install.tra is overwritten by worldmap.tra after the HANDLE_CHARSET took place. Let me fix that. I will come back to you.

**Comment by Roberciiik** [comment]
Hello @MephistoSatanDevil 
I fixed the English overwrite issue for Chinese language in #89. I've added a few new translations, so if you would like to update them, feel free to open a new pull request.

**Pull request merged**
